### ISSUE TITLE
Attribute Error: called_once_with is not a valid assertion

### ISSUE THREAD

**Issue by josdem** [josdem/py-vetlog-analyzer#33]
**Environment**
- Python version `3.12.3`
- Platform: Ubuntu `24.04`

**Steps to Reproduce**
- Setup environment variables: https://github.com/josdem/py-vetlog-analyzer/wiki/Configuration
- run tests with this command: `python3 -m unittest discover -s tests`

**Expected behaviour**
- All test are passing

**Actual result**
```bash
ERROR: test_mock_filter (test_mock_filter.FixedTest.test_mock_filter)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/josdem/Projects/py-vetlog-analyzer/tests/test_mock_filter.py", line 11, in test_mock_filter
    assert filter.cursor.execute.called_once_with("SELECT * FROM user")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/unittest/mock.py", line 663, in __getattr__
    raise AttributeError(
AttributeError: 'called_once_with' is not a valid assertion. Use a spec for the mock if 'called_once_with' is meant to be an attribute.. Did you mean: 'assert_called_once_with'?
```

**Comment by josdem** [comment]
PR merged: https://github.com/josdem/py-vetlog-analyzer/pull/34
